# FROM pytorch/pytorch:1.9.0-cuda11.1-cudnn8-runtime
# RUN apt update -y
# RUN apt install -y \
# wget \
# unzip
# WORKDIR /FEAT
# RUN pip install tensorflow wandb tensorboardX scipy pandas notebook json2html
# # RUN apt install tmux
# # RUN pip install wandb
# # RUN pip install tensorboardX
# # RUN pip install scipy